server:
  port: 8888

logging:
  path: ./logs
  level:
    edu.xidian.boot: debug

spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
    #初始化大小，最小，最大连接数
      initial-size: 5
      min-idle: 5
      max-active: 20
      #配置获取连接等待超时的时间
      max-wait: 60000
      #配置间隔多久进行一次检测，检测需要关闭的空闲连接，单位毫秒
      time-between-eviction-runs-millis: 60000
      #配置一个连接最小生存时间，单位毫秒
      min-evictable-idle-time-millis: 30000
      validation-query: SELECT VERSION()
    
mybatis:
  type-aliases-package: edu.xidian.boot.model
  mapper-locations: classpath:mappers/*.xml
