server:
  port: 8080

logging:
  level:
    edu.xidian.boot: debug
  file:
    path: ./logs

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo
    username: root
    password: 1qaz@WSX
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
    #初始化大小，最小，最大连接数
      initial-size: 5
      min-idle: 5
      max-active: 20
      #配置获取连接等待超时的时间
      max-wait: 60000
      #配置间隔多久进行一次检测，检测需要关闭的空闲连接，单位毫秒
      time-between-eviction-runs-millis: 60000
      #配置一个连接最小生存时间，单位毫秒
      min-evictable-idle-time-millis: 30000
      validation-query: SELECT VERSION()
  quartz:
    job-store-type: memory # Job存储类型，默认为memery，可选jdbc使用数据库
    auto-startup: true #是否自启动
    startup-delay: 0 # 延迟N秒启动
    wait-for-jobs-to-complete-on-shutdown: true #应用关闭时是否等待定时任务执行完成 默认false
    overwrite-existing-jobs: false # 是否覆盖已有Job配置
    properties:
      org:
        quartz:
          threadPool:
            threadCount: 25 #线程池大小，默认10
            threadPriority: 5 #线程优先级
            class: org.quartz.simpl.SimpleThreadPool # 线程池类型

mybatis:
  type-aliases-package: edu.xidian.boot.model
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mappers/*.xml
