spring:
  profiles:
    active:
    - dev
    
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis:
  type-aliases-package: edu.xidian.boot.model
  mapper-locations: classpath:mappers/*.xml